# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

# actions/deploy-pages.
permissions:
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Install Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 24.4.1
          cache: npm
      - name: Install Dependencies
        run: npm ci --no-fund
      - name: Lint
        run: npx lint
      - name: Build
        run: npx tsc --build
      - name: Unit Test
        run: npm run test:unit
      - name: Perf Test
        run: npm run test:perf
      - name: Upload schema/
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: schema/

  deploy:
    environment:
      name: github-pages
    # skip PRs.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/deploy-pages@v4.0.5
